import React, { useState } from 'react';
import { Code, TrendingUp, Database, Cpu, BarChart, Briefcase, GraduationCap, BookOpen, Play, Star, Clock, Users } from 'lucide-react';

const CoursesSection: React.FC = () => {
  const [selectedCategory, setSelectedCategory] = useState('B-Tech CSE');

  const categories = [
    { name: 'All', icon: BookOpen },
    { name: 'B-Tech CSE', icon: Code },
    { name: 'MBA', icon: Briefcase },
    { name: 'BCA/MCA', icon: Cpu },
    { name: 'Marketing', icon: TrendingUp },
    { name: 'Data Science', icon: Database },
    { name: 'MSc/BSc', icon: GraduationCap },
    { name: 'Diploma', icon: BarChart },
  ];

  const courses = [
    {
      id: 1,
      title: 'Advanced React Development',
      category: 'B-Tech CSE',
  image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Sarah Johnson',
      rating: 4.9,
      students: 2847,
      duration: '12 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Advanced',
      description: 'Master modern React development with hooks, context, and advanced patterns.',
      features: ['Live Projects', 'Industry Mentorship', 'Certificate'],
    },
    {
      id: 2,
      title: 'Strategic Business Management',
      category: 'MBA',
  image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Michael Chen',
      rating: 4.8,
      students: 1923,
      duration: '16 weeks',
      price: '$449',
      originalPrice: '$599',
      level: 'Intermediate',
      description: 'Comprehensive business strategy and management principles for modern leaders.',
      features: ['Case Studies', 'Real Business Projects', 'MBA Credit'],
    },
    {
      id: 3,
      title: 'Machine Learning Fundamentals',
      category: 'Data Science',
  image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Aisha Patel',
      rating: 4.9,
      students: 3156,
      duration: '14 weeks',
      price: '$349',
      originalPrice: '$499',
      level: 'Beginner',
      description: 'Learn ML algorithms, data preprocessing, and model deployment from scratch.',
      features: ['Hands-on Labs', 'Industry Projects', 'Job Assistance'],
    },
    {
      id: 4,
      title: 'Digital Marketing Mastery',
      category: 'Marketing',
  image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Maria Rodriguez',
      rating: 4.7,
      students: 2134,
      duration: '10 weeks',
      price: '$249',
      originalPrice: '$349',
      level: 'Intermediate',
      description: 'Complete digital marketing course covering SEO, SEM, social media, and analytics.',
      features: ['Live Campaigns', 'Google Certification', 'Portfolio Building'],
    },
    {
      id: 5,
      title: 'Database Design & Management',
      category: 'BCA/MCA',
      image: 'https://gvu57hqxi3.ufs.sh/f/FOd38ztMu1UwCauhEoUg9tzRh0wxOVZnsoTYDG7lE8daWHp3',
      instructor: 'Dr. James Wilson',
      rating: 4.8,
      students: 1876,
      duration: '8 weeks',
      price: '$199',
      originalPrice: '$299',
      level: 'Intermediate',
      description: 'Master database design, SQL, NoSQL, and database administration.',
      features: ['Practical Labs', 'Real Databases', 'Industry Tools'],
    },
    {
      id: 6,
      title: 'Research Methodology',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Sophie Mueller',
      rating: 4.6,
      students: 1456,
      duration: '6 weeks',
      price: '$149',
      originalPrice: '$199',
      level: 'Beginner',
      description: 'Essential research methods, data collection, and analysis techniques.',
      features: ['Research Tools', 'Publication Guide', 'Thesis Support'],
    },
    {
      id: 7,
      title: 'Full Stack JavaScript Development',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1619410283995-43d9134e7656?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Arjun Sharma',
      rating: 4.9,
      students: 3245,
      duration: '16 weeks',
      price: '$399',
      originalPrice: '$549',
      level: 'Intermediate',
      description: 'Master Node.js, Express, MongoDB, and React for complete web application development.',
      features: ['MERN Stack', 'Real Projects', 'Industry Mentorship'],
    },
    {
      id: 8,
      title: 'Data Structures & Algorithms',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rakesh Kumar',
      rating: 4.8,
      students: 4128,
      duration: '14 weeks',
      price: '$329',
      originalPrice: '$459',
      level: 'Advanced',
      description: 'Master essential DSA concepts for competitive programming and interviews.',
      features: ['Coding Practice', 'Interview Prep', 'FAANG Ready'],
    },
    {
      id: 9,
      title: 'Python Programming Masterclass',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Priya Singh',
      rating: 4.7,
      students: 2876,
      duration: '12 weeks',
      price: '$279',
      originalPrice: '$389',
      level: 'Beginner',
      description: 'Comprehensive Python course covering basics to advanced concepts and frameworks.',
      features: ['Django/Flask', 'Data Science', 'Web Scraping'],
    },
    {
      id: 10,
      title: 'Android App Development with Kotlin',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Vikash Gupta',
      rating: 4.8,
      students: 2134,
      duration: '10 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Intermediate',
      description: 'Build modern Android apps using Kotlin, Jetpack Compose, and latest Android APIs.',
      features: ['Play Store Publishing', 'Material Design', 'Firebase Integration'],
    },
    {
      id: 11,
      title: 'DevOps & Cloud Computing',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Amit Verma',
      rating: 4.9,
      students: 1967,
      duration: '12 weeks',
      price: '$379',
      originalPrice: '$499',
      level: 'Advanced',
      description: 'Learn Docker, Kubernetes, AWS, CI/CD pipelines and modern deployment strategies.',
      features: ['AWS Certification', 'Hands-on Labs', 'Industry Projects'],
    },
    {
      id: 12,
      title: 'Cybersecurity Fundamentals',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Neha Agarwal',
      rating: 4.7,
      students: 1845,
      duration: '8 weeks',
      price: '$249',
      originalPrice: '$349',
      level: 'Beginner',
      description: 'Essential cybersecurity concepts, ethical hacking, and network security principles.',
      features: ['Penetration Testing', 'Security Tools', 'Certification Prep'],
    },
    {
      id: 13,
      title: 'Artificial Intelligence & Machine Learning',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Rajesh Khanna',
      rating: 4.9,
      students: 3567,
      duration: '16 weeks',
      price: '$449',
      originalPrice: '$599',
      level: 'Advanced',
      description: 'Deep dive into AI/ML algorithms, neural networks, and practical implementations.',
      features: ['TensorFlow/PyTorch', 'Computer Vision', 'NLP Projects'],
    },
    {
      id: 14,
      title: 'Software Engineering & Design Patterns',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Sunita Sharma',
      rating: 4.6,
      students: 1623,
      duration: '10 weeks',
      price: '$229',
      originalPrice: '$319',
      level: 'Intermediate',
      description: 'Learn software engineering principles, design patterns, and best practices.',
      features: ['System Design', 'Code Review', 'Agile Methodology'],
    },
    {
      id: 15,
      title: 'Blockchain Technology & Cryptocurrency',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Rohit Mehra',
      rating: 4.8,
      students: 1456,
      duration: '8 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Intermediate',
      description: 'Understand blockchain fundamentals, smart contracts, and DeFi applications.',
      features: ['Smart Contracts', 'Solidity', 'Web3 Development'],
    },
    {
      id: 16,
      title: 'Game Development with Unity',
      category: 'B-Tech CSE',
      image: 'https://images.unsplash.com/photo-1556438064-2d7646166914?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Karan Singh',
      rating: 4.7,
      students: 1287,
      duration: '12 weeks',
      price: '$349',
      originalPrice: '$449',
      level: 'Beginner',
      description: 'Create engaging 2D and 3D games using Unity engine and C# programming.',
      features: ['2D/3D Games', 'Physics Engine', 'Mobile Publishing'],
    },
    // MBA Courses
    {
      id: 17,
      title: 'Digital Marketing Strategy',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Anita Gupta',
      rating: 4.8,
      students: 2156,
      duration: '8 weeks',
      price: '$329',
      originalPrice: '$429',
      level: 'Intermediate',
      description: 'Master digital marketing strategies, SEO, SEM, social media, and analytics for business growth.',
      features: ['Google Analytics', 'ROI Optimization', 'Campaign Management'],
    },
    {
      id: 18,
      title: 'Financial Management & Analysis',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Rajesh Agarwal',
      rating: 4.9,
      students: 1834,
      duration: '12 weeks',
      price: '$399',
      originalPrice: '$529',
      level: 'Advanced',
      description: 'Comprehensive financial planning, investment analysis, and corporate finance strategies.',
      features: ['Portfolio Management', 'Risk Analysis', 'Financial Modeling'],
    },
    {
      id: 19,
      title: 'Operations Management',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Sanjay Kumar',
      rating: 4.7,
      students: 1567,
      duration: '10 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Intermediate',
      description: 'Optimize business operations, supply chain management, and process improvement strategies.',
      features: ['Lean Six Sigma', 'Supply Chain', 'Quality Management'],
    },
    {
      id: 20,
      title: 'Human Resource Management',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Meera Sharma',
      rating: 4.6,
      students: 1945,
      duration: '8 weeks',
      price: '$249',
      originalPrice: '$349',
      level: 'Beginner',
      description: 'Master HR strategies, talent acquisition, performance management, and organizational behavior.',
      features: ['Talent Management', 'Leadership Skills', 'Employee Engagement'],
    },
    {
      id: 21,
      title: 'Data Analytics for Business',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Vikram Singh',
      rating: 4.8,
      students: 2234,
      duration: '10 weeks',
      price: '$349',
      originalPrice: '$459',
      level: 'Intermediate',
      description: 'Learn business intelligence, data visualization, and predictive analytics for decision making.',
      features: ['Tableau/Power BI', 'Statistical Analysis', 'Business Intelligence'],
    },
    {
      id: 22,
      title: 'International Business Strategy',
      category: 'MBA',
      image: 'https://gvu57hqxi3.ufs.sh/f/FOd38ztMu1UwCgvw48Ug9tzRh0wxOVZnsoTYDG7lE8daWHp3',
      instructor: 'Dr. Priya Mehta',
      rating: 4.7,
      students: 1456,
      duration: '12 weeks',
      price: '$379',
      originalPrice: '$499',
      level: 'Advanced',
      description: 'Global business strategies, international trade, cross-cultural management, and market entry.',
      features: ['Global Markets', 'Cross-Cultural Skills', 'Trade Regulations'],
    },
    {
      id: 23,
      title: 'Entrepreneurship & Innovation',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Rohit Bansal',
      rating: 4.9,
      students: 1723,
      duration: '8 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Beginner',
      description: 'Build your startup from idea to execution with business planning and innovation strategies.',
      features: ['Business Plan', 'Funding Strategies', 'Market Validation'],
    },
    {
      id: 24,
      title: 'Project Management Professional',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Ashok Kumar',
      rating: 4.8,
      students: 2087,
      duration: '10 weeks',
      price: '$359',
      originalPrice: '$479',
      level: 'Intermediate',
      description: 'Master project management methodologies, Agile, Scrum, and PMP certification preparation.',
      features: ['PMP Certification', 'Agile/Scrum', 'Risk Management'],
    },
    {
      id: 25,
      title: 'Corporate Finance & Investment',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Suresh Gupta',
      rating: 4.7,
      students: 1634,
      duration: '12 weeks',
      price: '$399',
      originalPrice: '$529',
      level: 'Advanced',
      description: 'Advanced corporate finance, mergers & acquisitions, and investment banking strategies.',
      features: ['M&A Analysis', 'Valuation Models', 'Investment Banking'],
    },
    {
      id: 26,
      title: 'Leadership & Organizational Behavior',
      category: 'MBA',
      image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Kavita Singh',
      rating: 4.6,
      students: 1798,
      duration: '8 weeks',
      price: '$279',
      originalPrice: '$369',
      level: 'Beginner',
      description: 'Develop leadership skills, team management, and understanding of organizational dynamics.',
      features: ['Leadership Skills', 'Team Building', 'Change Management'],
    },
    // BCA/MCA Courses
    {
      id: 27,
      title: 'Java Programming & Spring Framework',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Ravi Kumar',
      rating: 4.8,
      students: 2456,
      duration: '14 weeks',
      price: '$329',
      originalPrice: '$449',
      level: 'Intermediate',
      description: 'Master Java fundamentals, OOP concepts, and Spring Boot for enterprise application development.',
      features: ['Spring Boot', 'Microservices', 'REST APIs'],
    },
    {
      id: 28,
      title: 'MySQL & Database Administration',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Amit Sharma',
      rating: 4.7,
      students: 1987,
      duration: '10 weeks',
      price: '$249',
      originalPrice: '$349',
      level: 'Beginner',
      description: 'Complete MySQL course covering database design, optimization, and administration.',
      features: ['Database Design', 'Performance Tuning', 'Backup & Recovery'],
    },
    {
      id: 29,
      title: 'PHP & Laravel Web Development',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Deepak Gupta',
      rating: 4.6,
      students: 1723,
      duration: '12 weeks',
      price: '$279',
      originalPrice: '$379',
      level: 'Intermediate',
      description: 'Build dynamic web applications using PHP and Laravel framework with modern practices.',
      features: ['Laravel Framework', 'MVC Architecture', 'Payment Integration'],
    },
    {
      id: 30,
      title: 'Data Structures with C++',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Neha Singh',
      rating: 4.9,
      students: 2134,
      duration: '12 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Advanced',
      description: 'Master data structures and algorithms using C++ for competitive programming and interviews.',
      features: ['STL Libraries', 'Algorithm Analysis', 'Competitive Programming'],
    },
    {
      id: 31,
      title: 'Web Development with React & Node.js',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Priya Sharma',
      rating: 4.8,
      students: 1856,
      duration: '16 weeks',
      price: '$379',
      originalPrice: '$509',
      level: 'Intermediate',
      description: 'Full-stack web development with React frontend and Node.js backend development.',
      features: ['React Hooks', 'Express.js', 'MongoDB Integration'],
    },
    {
      id: 32,
      title: 'Computer Networks & Security',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rajesh Kumar',
      rating: 4.7,
      students: 1645,
      duration: '10 weeks',
      price: '$269',
      originalPrice: '$369',
      level: 'Intermediate',
      description: 'Comprehensive networking concepts, protocols, and cybersecurity fundamentals.',
      features: ['Network Protocols', 'Firewall Configuration', 'Penetration Testing'],
    },
    {
      id: 33,
      title: 'Software Testing & Quality Assurance',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Sunita Agarwal',
      rating: 4.6,
      students: 1434,
      duration: '8 weeks',
      price: '$229',
      originalPrice: '$319',
      level: 'Beginner',
      description: 'Learn manual and automated testing techniques, test planning, and quality assurance processes.',
      features: ['Selenium Testing', 'Test Automation', 'Bug Tracking'],
    },
    {
      id: 34,
      title: 'Mobile App Development with Flutter',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Vikash Singh',
      rating: 4.8,
      students: 1567,
      duration: '12 weeks',
      price: '$319',
      originalPrice: '$439',
      level: 'Intermediate',
      description: 'Build cross-platform mobile applications using Flutter and Dart programming language.',
      features: ['Cross-platform Development', 'Firebase Integration', 'App Store Publishing'],
    },
    {
      id: 35,
      title: 'Linux System Administration',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Arun Kumar',
      rating: 4.7,
      students: 1298,
      duration: '8 weeks',
      price: '$199',
      originalPrice: '$279',
      level: 'Beginner',
      description: 'Master Linux commands, shell scripting, and system administration for server management.',
      features: ['Shell Scripting', 'Server Management', 'System Security'],
    },
    {
      id: 36,
      title: 'Cloud Computing with AWS',
      category: 'BCA/MCA',
      image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Kavita Gupta',
      rating: 4.9,
      students: 1876,
      duration: '10 weeks',
      price: '$349',
      originalPrice: '$469',
      level: 'Advanced',
      description: 'Learn Amazon Web Services, cloud architecture, and deployment strategies.',
      features: ['AWS Certification', 'Cloud Architecture', 'Serverless Computing'],
    },
    // Marketing Courses
    {
      id: 37,
      title: 'Social Media Marketing Mastery',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Ms. Priya Sharma',
      rating: 4.8,
      students: 2345,
      duration: '8 weeks',
      price: '$229',
      originalPrice: '$319',
      level: 'Beginner',
      description: 'Master Facebook, Instagram, LinkedIn, Twitter marketing with content strategy and paid advertising.',
      features: ['Content Creation', 'Paid Advertising', 'Analytics & ROI'],
    },
    {
      id: 38,
      title: 'Search Engine Optimization (SEO)',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Rohit Gupta',
      rating: 4.7,
      students: 1987,
      duration: '10 weeks',
      price: '$279',
      originalPrice: '$379',
      level: 'Intermediate',
      description: 'Complete SEO course covering keyword research, on-page, off-page, and technical SEO strategies.',
      features: ['Keyword Research', 'Link Building', 'Google Analytics'],
    },
    {
      id: 39,
      title: 'Email Marketing & Automation',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Neha Agarwal',
      rating: 4.6,
      students: 1654,
      duration: '6 weeks',
      price: '$199',
      originalPrice: '$279',
      level: 'Beginner',
      description: 'Build effective email campaigns, automation workflows, and customer journey mapping.',
      features: ['Campaign Automation', 'A/B Testing', 'Customer Segmentation'],
    },
    {
      id: 40,
      title: 'Content Marketing Strategy',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Vikash Kumar',
      rating: 4.8,
      students: 1876,
      duration: '8 weeks',
      price: '$249',
      originalPrice: '$349',
      level: 'Intermediate',
      description: 'Create compelling content strategies, storytelling, and content distribution across multiple channels.',
      features: ['Content Strategy', 'Storytelling', 'Multi-channel Distribution'],
    },
    {
      id: 41,
      title: 'Google Ads & PPC Marketing',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Ms. Anita Singh',
      rating: 4.9,
      students: 2198,
      duration: '10 weeks',
      price: '$329',
      originalPrice: '$449',
      level: 'Advanced',
      description: 'Master Google Ads, Bing Ads, and PPC strategies for maximum ROI and conversion optimization.',
      features: ['Google Ads Certification', 'Conversion Tracking', 'Bid Management'],
    },
    {
      id: 42,
      title: 'Affiliate Marketing & Partnerships',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Deepak Mehta',
      rating: 4.7,
      students: 1543,
      duration: '8 weeks',
      price: '$269',
      originalPrice: '$369',
      level: 'Intermediate',
      description: 'Build profitable affiliate marketing programs and strategic partnerships for business growth.',
      features: ['Affiliate Networks', 'Commission Structures', 'Partnership Strategy'],
    },
    {
      id: 43,
      title: 'E-commerce Marketing',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Kavita Sharma',
      rating: 4.8,
      students: 1765,
      duration: '12 weeks',
      price: '$359',
      originalPrice: '$479',
      level: 'Advanced',
      description: 'Comprehensive e-commerce marketing covering Amazon, Shopify, conversion optimization, and sales funnels.',
      features: ['Amazon Marketing', 'Conversion Optimization', 'Sales Funnels'],
    },
    {
      id: 44,
      title: 'Brand Management & Strategy',
      category: 'Marketing',
      image: 'https://gvu57hqxi3.ufs.sh/f/FOd38ztMu1UwgsFa3vlvY0wJSo9cuVLWG2rpHtCOfq6IZi1T',
      instructor: 'Prof. Rajesh Kumar',
      rating: 4.6,
      students: 1432,
      duration: '10 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Intermediate',
      description: 'Build strong brand identity, positioning, and long-term brand strategy for competitive advantage.',
      features: ['Brand Positioning', 'Brand Identity', 'Competitive Analysis'],
    },
    {
      id: 45,
      title: 'Marketing Analytics & Data-Driven Marketing',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Amit Verma',
      rating: 4.9,
      students: 2087,
      duration: '12 weeks',
      price: '$379',
      originalPrice: '$509',
      level: 'Advanced',
      description: 'Master marketing analytics, attribution modeling, and data-driven decision making for campaigns.',
      features: ['Google Analytics 4', 'Attribution Modeling', 'Marketing ROI'],
    },
    {
      id: 46,
      title: 'Influencer Marketing Strategy',
      category: 'Marketing',
      image: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Ms. Shreya Patel',
      rating: 4.7,
      students: 1654,
      duration: '6 weeks',
      price: '$219',
      originalPrice: '$299',
      level: 'Beginner',
      description: 'Learn influencer identification, campaign management, and ROI measurement for influencer marketing.',
      features: ['Influencer Outreach', 'Campaign Management', 'Performance Tracking'],
    },
    // Data Science Courses
    {
      id: 47,
      title: 'Python for Data Science',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Arjun Kumar',
      rating: 4.9,
      students: 3245,
      duration: '12 weeks',
      price: '$329',
      originalPrice: '$449',
      level: 'Beginner',
      description: 'Master Python programming for data science with pandas, NumPy, and data visualization libraries.',
      features: ['Pandas & NumPy', 'Data Visualization', 'Jupyter Notebooks'],
    },
    {
      id: 48,
      title: 'Deep Learning with TensorFlow',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Priya Singh',
      rating: 4.8,
      students: 2567,
      duration: '16 weeks',
      price: '$449',
      originalPrice: '$599',
      level: 'Advanced',
      description: 'Build neural networks, CNNs, RNNs using TensorFlow and Keras for real-world applications.',
      features: ['Neural Networks', 'Computer Vision', 'Natural Language Processing'],
    },
    {
      id: 49,
      title: 'Data Visualization with Tableau',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Vikash Sharma',
      rating: 4.7,
      students: 1987,
      duration: '8 weeks',
      price: '$279',
      originalPrice: '$379',
      level: 'Intermediate',
      description: 'Create interactive dashboards and compelling data visualizations using Tableau Desktop and Server.',
      features: ['Interactive Dashboards', 'Advanced Charts', 'Data Storytelling'],
    },
    {
      id: 50,
      title: 'Statistical Analysis with R',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Neha Gupta',
      rating: 4.6,
      students: 1765,
      duration: '10 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Intermediate',
      description: 'Master statistical analysis, hypothesis testing, and data modeling using R programming language.',
      features: ['Statistical Testing', 'Data Modeling', 'R Shiny Apps'],
    },
    {
      id: 51,
      title: 'Big Data Analytics with Spark',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rajesh Agarwal',
      rating: 4.8,
      students: 1543,
      duration: '12 weeks',
      price: '$379',
      originalPrice: '$509',
      level: 'Advanced',
      description: 'Process and analyze large datasets using Apache Spark, Hadoop, and distributed computing.',
      features: ['Apache Spark', 'Hadoop Ecosystem', 'Distributed Computing'],
    },
    {
      id: 52,
      title: 'Business Intelligence & ETL',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Sunita Sharma',
      rating: 4.7,
      students: 1654,
      duration: '10 weeks',
      price: '$319',
      originalPrice: '$439',
      level: 'Intermediate',
      description: 'Build data warehouses, ETL pipelines, and business intelligence solutions for enterprise data.',
      features: ['Data Warehousing', 'ETL Processes', 'Power BI'],
    },
    {
      id: 53,
      title: 'Natural Language Processing',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Amit Singh',
      rating: 4.9,
      students: 1876,
      duration: '14 weeks',
      price: '$399',
      originalPrice: '$529',
      level: 'Advanced',
      description: 'Master text processing, sentiment analysis, chatbots, and language models using NLP techniques.',
      features: ['Text Processing', 'Sentiment Analysis', 'Language Models'],
    },
    {
      id: 54,
      title: 'Time Series Analysis & Forecasting',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Kavita Kumar',
      rating: 4.8,
      students: 1432,
      duration: '10 weeks',
      price: '$339',
      originalPrice: '$459',
      level: 'Advanced',
      description: 'Learn time series analysis, forecasting models, and predictive analytics for business applications.',
      features: ['ARIMA Models', 'Seasonal Forecasting', 'Prophet Framework'],
    },
    {
      id: 55,
      title: 'Computer Vision & Image Processing',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Rohit Mehta',
      rating: 4.7,
      students: 1567,
      duration: '12 weeks',
      price: '$359',
      originalPrice: '$479',
      level: 'Advanced',
      description: 'Build computer vision applications using OpenCV, image classification, and object detection models.',
      features: ['OpenCV', 'Object Detection', 'Image Classification'],
    },
    {
      id: 56,
      title: 'Data Engineering & Pipeline Design',
      category: 'Data Science',
      image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Deepak Kumar',
      rating: 4.6,
      students: 1298,
      duration: '14 weeks',
      price: '$379',
      originalPrice: '$509',
      level: 'Advanced',
      description: 'Design and build scalable data pipelines, data lakes, and modern data architecture.',
      features: ['Data Pipelines', 'Data Lakes', 'Cloud Data Services'],
    },
    // MSc/BSc Courses
    {
      id: 57,
      title: 'Advanced Mathematics for Scientists',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rajesh Kumar',
      rating: 4.7,
      students: 1567,
      duration: '12 weeks',
      price: '$279',
      originalPrice: '$379',
      level: 'Advanced',
      description: 'Master calculus, linear algebra, differential equations, and statistical methods for scientific applications.',
      features: ['Mathematical Modeling', 'Statistical Analysis', 'Problem Solving'],
    },
    {
      id: 58,
      title: 'Laboratory Techniques & Instrumentation',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Priya Sharma',
      rating: 4.8,
      students: 1345,
      duration: '10 weeks',
      price: '$329',
      originalPrice: '$449',
      level: 'Intermediate',
      description: 'Learn modern laboratory techniques, instrumentation, and data analysis for scientific research.',
      features: ['Lab Safety', 'Data Collection', 'Instrument Calibration'],
    },
    {
      id: 59,
      title: 'Scientific Writing & Publication',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Neha Agarwal',
      rating: 4.6,
      students: 987,
      duration: '8 weeks',
      price: '$199',
      originalPrice: '$279',
      level: 'Beginner',
      description: 'Master scientific writing, research paper structure, and publication process for academic journals.',
      features: ['Academic Writing', 'Peer Review Process', 'Citation Management'],
    },
    {
      id: 60,
      title: 'Bioinformatics & Computational Biology',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Amit Singh',
      rating: 4.9,
      students: 1234,
      duration: '14 weeks',
      price: '$379',
      originalPrice: '$509',
      level: 'Advanced',
      description: 'Apply computational methods to biological data analysis, genomics, and protein structure prediction.',
      features: ['Genome Analysis', 'Protein Modeling', 'Phylogenetic Analysis'],
    },
    {
      id: 61,
      title: 'Environmental Science & Sustainability',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1569163139394-de4e5f43e4e3?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Sunita Kumar',
      rating: 4.7,
      students: 1456,
      duration: '10 weeks',
      price: '$249',
      originalPrice: '$349',
      level: 'Intermediate',
      description: 'Study environmental systems, climate change, pollution control, and sustainable development practices.',
      features: ['Climate Analysis', 'Pollution Control', 'Sustainability Planning'],
    },
    {
      id: 62,
      title: 'Organic Chemistry & Synthesis',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Kavita Gupta',
      rating: 4.8,
      students: 1678,
      duration: '12 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Advanced',
      description: 'Master organic reaction mechanisms, synthesis strategies, and modern analytical techniques.',
      features: ['Reaction Mechanisms', 'Synthetic Pathways', 'NMR Spectroscopy'],
    },
    {
      id: 63,
      title: 'Physics: Quantum Mechanics & Applications',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Vikash Sharma',
      rating: 4.6,
      students: 1123,
      duration: '14 weeks',
      price: '$349',
      originalPrice: '$459',
      level: 'Advanced',
      description: 'Explore quantum mechanics principles, wave functions, and applications in modern technology.',
      features: ['Wave Functions', 'Quantum States', 'Modern Applications'],
    },
    {
      id: 64,
      title: 'Microbiology & Immunology',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Meera Singh',
      rating: 4.8,
      students: 1389,
      duration: '10 weeks',
      price: '$289',
      originalPrice: '$389',
      level: 'Intermediate',
      description: 'Study microorganisms, immune system functions, and disease mechanisms at molecular level.',
      features: ['Pathogen Analysis', 'Immune Response', 'Molecular Biology'],
    },
    {
      id: 65,
      title: 'Analytical Chemistry & Spectroscopy',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1628595351029-c2bf17511435?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rohit Kumar',
      rating: 4.7,
      students: 1234,
      duration: '8 weeks',
      price: '$259',
      originalPrice: '$349',
      level: 'Intermediate',
      description: 'Master analytical techniques including UV-Vis, IR, NMR, and mass spectrometry for chemical analysis.',
      features: ['Spectroscopic Methods', 'Quantitative Analysis', 'Method Validation'],
    },
    {
      id: 66,
      title: 'Biotechnology & Genetic Engineering',
      category: 'MSc/BSc',
      image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Anita Sharma',
      rating: 4.9,
      students: 1567,
      duration: '12 weeks',
      price: '$339',
      originalPrice: '$449',
      level: 'Advanced',
      description: 'Explore genetic engineering techniques, CRISPR, cloning, and biotechnology applications.',
      features: ['CRISPR Technology', 'Gene Cloning', 'Biotech Applications'],
    },
    // Diploma Courses
    {
      id: 67,
      title: 'Mechanical Engineering Fundamentals',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rajesh Verma',
      rating: 4.7,
      students: 1876,
      duration: '16 weeks',
      price: '$329',
      originalPrice: '$449',
      level: 'Beginner',
      description: 'Learn mechanical engineering principles, thermodynamics, fluid mechanics, and machine design.',
      features: ['CAD Design', 'Material Science', 'Manufacturing Processes'],
    },
    {
      id: 68,
      title: 'Electrical & Electronics Engineering',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Priya Kumar',
      rating: 4.8,
      students: 1654,
      duration: '14 weeks',
      price: '$299',
      originalPrice: '$399',
      level: 'Intermediate',
      description: 'Master electrical circuits, electronic devices, power systems, and control engineering.',
      features: ['Circuit Analysis', 'Power Systems', 'Control Systems'],
    },
    {
      id: 69,
      title: 'Civil Engineering & Construction',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Amit Singh',
      rating: 4.6,
      students: 1432,
      duration: '18 weeks',
      price: '$359',
      originalPrice: '$479',
      level: 'Beginner',
      description: 'Learn structural engineering, construction management, surveying, and building design principles.',
      features: ['Structural Design', 'Construction Planning', 'AutoCAD'],
    },
    {
      id: 70,
      title: 'Computer Hardware & Networking',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Vikash Gupta',
      rating: 4.7,
      students: 1789,
      duration: '12 weeks',
      price: '$279',
      originalPrice: '$379',
      level: 'Intermediate',
      description: 'Master computer hardware troubleshooting, network setup, and system administration.',
      features: ['Hardware Troubleshooting', 'Network Configuration', 'System Maintenance'],
    },
    {
      id: 71,
      title: 'Automobile Engineering & Mechanics',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Deepak Kumar',
      rating: 4.8,
      students: 1345,
      duration: '16 weeks',
      price: '$339',
      originalPrice: '$459',
      level: 'Intermediate',
      description: 'Learn automobile systems, engine mechanics, diagnostics, and modern vehicle technology.',
      features: ['Engine Diagnostics', 'Vehicle Systems', 'Modern Technology'],
    },
    {
      id: 72,
      title: 'Welding & Fabrication Technology',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Mr. Suresh Singh',
      rating: 4.6,
      students: 987,
      duration: '10 weeks',
      price: '$249',
      originalPrice: '$329',
      level: 'Beginner',
      description: 'Master welding techniques, metal fabrication, and industrial manufacturing processes.',
      features: ['Arc Welding', 'Metal Fabrication', 'Safety Procedures'],
    },
    {
      id: 73,
      title: 'HVAC & Refrigeration Systems',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1621905252472-e8de73cbf4c6?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Kavita Sharma',
      rating: 4.7,
      students: 1234,
      duration: '12 weeks',
      price: '$289',
      originalPrice: '$389',
      level: 'Intermediate',
      description: 'Learn heating, ventilation, air conditioning, and refrigeration system design and maintenance.',
      features: ['System Design', 'Maintenance Procedures', 'Energy Efficiency'],
    },
    {
      id: 74,
      title: 'Electronics & Communication Technology',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Neha Kumar',
      rating: 4.8,
      students: 1567,
      duration: '14 weeks',
      price: '$309',
      originalPrice: '$419',
      level: 'Intermediate',
      description: 'Master electronic circuits, communication systems, and modern telecommunication technology.',
      features: ['Communication Systems', 'Signal Processing', 'Telecommunication'],
    },
    {
      id: 75,
      title: 'Industrial Automation & PLC Programming',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Prof. Rohit Verma',
      rating: 4.9,
      students: 1456,
      duration: '10 weeks',
      price: '$319',
      originalPrice: '$429',
      level: 'Advanced',
      description: 'Learn industrial automation, PLC programming, SCADA systems, and process control.',
      features: ['PLC Programming', 'SCADA Systems', 'Process Control'],
    },
    {
      id: 76,
      title: 'Quality Control & Testing Methods',
      category: 'Diploma',
      image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80&fm=webp',
      instructor: 'Dr. Sunita Gupta',
      rating: 4.6,
      students: 1123,
      duration: '8 weeks',
      price: '$229',
      originalPrice: '$309',
      level: 'Beginner',
      description: 'Master quality control techniques, testing methods, and industrial standards compliance.',
      features: ['Quality Standards', 'Testing Procedures', 'Compliance Management'],
    },
  ];

  const filteredCourses = selectedCategory === 'All' 
    ? courses 
    : courses.filter(course => course.category === selectedCategory);

  return (
    <section id="courses" className="py-20 bg-gradient-to-br from-neutral-50 to-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="font-heading text-3xl sm:text-4xl font-bold text-primary-dark mb-4">
            Master Skills That Matter
          </h2>
          <p className="text-lg text-neutral-600 max-w-2xl mx-auto mb-8">
            Comprehensive courses designed by industry experts to accelerate your academic and professional growth.
          </p>
          <button 
            onClick={() => window.location.href = '/payment'}
            className="bg-gradient-to-r from-primary-dark to-accent-teal text-white font-heading font-bold px-8 py-4 rounded-full hover:shadow-2xl hover:scale-105 transition-all duration-300 animate-glow"
          >
            Start Learning Today →
          </button>
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-4 mb-12">
          {categories.map((category, index) => (
            <button
              key={index}
              onClick={() => setSelectedCategory(category.name)}
              className={`flex items-center space-x-2 px-6 py-3 rounded-full font-medium transition-all duration-300 ${
                selectedCategory === category.name
                  ? 'bg-gradient-to-r from-primary-dark to-accent-teal text-white shadow-lg'
                  : 'bg-white text-neutral-600 hover:bg-neutral-50 border border-neutral-200'
              }`}
            >
              <category.icon className="h-5 w-5" />
              <span>{category.name}</span>
            </button>
          ))}
        </div>

        {/* Courses Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredCourses.map((course, index) => (
            <div
              key={course.id}
              className="bg-white rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 overflow-hidden border border-neutral-100 group animate-fade-in-up"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              {/* Course Image */}
              <div className="relative overflow-hidden">
                <img
                  src={course.image}
                  alt={course.title}
                  loading="lazy"
                  className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/30 to-transparent"></div>
                <div className="absolute top-4 left-4 bg-accent-teal text-white px-3 py-1 rounded-full text-sm font-bold">
                  {course.level}
                </div>
                <div className="absolute top-4 right-4 bg-white/90 backdrop-blur-sm rounded-full p-2">
                  <Play className="h-5 w-5 text-primary-dark" />
                </div>
                <div className="absolute bottom-4 left-4 flex items-center space-x-2">
                  <div className="flex text-yellow-400">
                    {[...Array(5)].map((_, i) => (
                      <Star key={i} className={`h-4 w-4 ${i < Math.floor(course.rating) ? 'fill-current' : ''}`} />
                    ))}
                  </div>
                  <span className="text-white text-sm font-medium">{course.rating}</span>
                </div>
              </div>

              {/* Course Content */}
              <div className="p-6">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-accent-teal text-sm font-medium">{course.category}</span>
                  <div className="flex items-center space-x-1 text-neutral-500 text-sm">
                    <Users className="h-4 w-4" />
                    <span>{course.students.toLocaleString()}</span>
                  </div>
                </div>

                <h3 className="font-heading text-lg font-bold text-primary-dark mb-2 line-clamp-2">
                  {course.title}
                </h3>

                <p className="text-neutral-600 text-sm mb-4 line-clamp-2">
                  {course.description}
                </p>

                <div className="flex items-center space-x-4 mb-4 text-sm text-neutral-500">
                  <div className="flex items-center space-x-1">
                    <Clock className="h-4 w-4" />
                    <span>{course.duration}</span>
                  </div>
                  <div className="flex items-center space-x-1">
                    <GraduationCap className="h-4 w-4" />
                    <span>{course.instructor}</span>
                  </div>
                </div>

                <div className="flex flex-wrap gap-2 mb-4">
                  {course.features.map((feature, idx) => (
                    <span key={idx} className="bg-neutral-100 text-neutral-600 px-2 py-1 rounded-full text-xs">
                      {feature}
                    </span>
                  ))}
                </div>

                <div className="flex items-center justify-end">
                  <button 
                    onClick={() => window.open('https://wa.me/919217189006?text=Hi, I want to enroll in ' + course.title, '_blank')}
                    className="bg-gradient-to-r from-primary-dark to-accent-teal text-white font-medium px-6 py-2 rounded-full hover:shadow-lg hover:scale-105 transition-all duration-300"
                  >
                    Enroll Now
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Limited Time Offer */}
        {/* <div className="mt-16 bg-gradient-to-r from-primary-dark to-accent-teal rounded-3xl p-8 text-center text-white">
          <h3 className="font-heading text-2xl font-bold mb-4">
            🎉 Limited Time Offer - Save 25% on All Courses!
          </h3>
          <p className="text-lg mb-6 text-white/90">
            Enroll in any course today and get instant access to premium content and expert mentorship.
          </p>
          <div className="flex items-center justify-center space-x-4 mb-6">
            <div className="bg-white/20 backdrop-blur-sm rounded-lg p-4">
              <div className="text-2xl font-bold">23</div>
              <div className="text-sm">Hours</div>
            </div>
            <div className="bg-white/20 backdrop-blur-sm rounded-lg p-4">
              <div className="text-2xl font-bold">45</div>
              <div className="text-sm">Minutes</div>
            </div>
            <div className="bg-white/20 backdrop-blur-sm rounded-lg p-4">
              <div className="text-2xl font-bold">12</div>
              <div className="text-sm">Seconds</div>
            </div>
          </div>
          <button 
            onClick={() => window.location.href = '/payment'}
            className="bg-white text-primary-dark font-heading font-bold px-8 py-4 rounded-full hover:shadow-2xl hover:scale-105 transition-all duration-300"
          >
            Claim Your Discount Now →
          </button>
        </div> */}
      </div>
    </section>
  );
};

export default CoursesSection;